---
title: "finalproject"
author: "Rachel Lee"
date: "1/16/2020"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(data.table)
library(patchwork)
```

```{r}

final_tuesday = final %>% 
  janitor::clean_names() %>% 
  mutate_at(vars(starts_with("est")), as.numeric) %>% 
  pivot_longer(cols = starts_with("est"), names_to = "gender", values_to = "number", values_drop_na = FALSE)

```

```{r}
final = read_excel("./data/median-earnings-2016-final.xlsx", sheet =1, range = "A5:Q563") %>% 
  janitor::clean_names() %>% 
  select(-starts_with("moe")) 

final_num = final %>% 
  select(-ends_with("med")) %>% 
  pivot_longer(cols = starts_with("est"), names_to = "gender", values_to = "number", values_drop_na = FALSE) %>% 
  filter(occupational_category %in% c("Management, Business, Science, and Arts Occupations", "Service Occupations", "Sales and Office Occupations", "Natural Resources, Construction, and Maintenance Occupations", "Production, Transportation, and Material Moving Occupations")) %>% 
  filter(gender %in% c("est_men_num", "est_women_num")) %>% 
  



final_med = final %>% 
  select(-ends_with("num")) %>% 
  mutate_at(vars(starts_with("est")), as.numeric) %>% 
  pivot_longer(cols = starts_with("est"), names_to = "gender", values_to = "number", values_drop_na = FALSE) %>% 
  filter(occupational_category %in% c("Management, Business, Science, and Arts Occupations", "Service Occupations", "Sales and Office Occupations", "Natural Resources, Construction, and Maintenance Occupations", "Production, Transportation, and Material Moving Occupations")) %>% 
  filter(gender %in% c("est_men_med", "est_women_med")) %>% 
  group_by(occupational_category) %>% 
  ggplot(aes(x = gender, y = number, fill = occupational_category)) +
  geom_bar(stat = "identity", position = "dodge") +
  scale_fill_grey() +
  theme(axis.text.x = element_text(size=10))
  
final_med + final_num

final2 = final_1
colnames(final2) <- final2[1,]
final2 <- final2[-1, ] 

final2 <- data.frame(names = row.names(final2), final2)
rownames(final2) = 1:nrow(final2)

final2 = final2 %>% mutate_if(is.character,as.numeric)

total_num <- final2[1:3,]
plot = total_num %>% 
  mutate(names = as.factor(names)) %>% 
  ggplot(aes(x = names, y = Total, fill = Total)) +
  geom_bar(stat ="identity", position = "dodge")

final_selected = final2 %>% 
  select(names, Total, Management..Business..Science..and.Arts.Occupations ) %>% 
  ggplot(aes(x = ))

```

```{r}
rownames(final_1) = (col_number, 1)
```


